name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      testFile:
        description: '/tests/specs/*.spec.ts)'
        required: false
        default: ''
      browser:
        description: 'Browser to run on (chromium, firefox, edge)'
        required: false
        default: 'chromium'

jobs:
  tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      BASE_URL: ${{ vars.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: |
          npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
